// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Chat struct {
	ID        string    `json:"id"`
	FromUser  string    `json:"from_user"`
	ToUser    string    `json:"to_user"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
}

type ContactList struct {
	Username       string `json:"username"`
	MemberUsername string `json:"member_username"`
	LastActivity   int64  `json:"last_activity"`
}

type User struct {
	Username          string    `json:"username"`
	Password          string    `json:"password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
