// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	AddContact(ctx context.Context, arg AddContactParams) (ContactList, error)
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetChatHistory(ctx context.Context, arg GetChatHistoryParams) ([]Chat, error)
	GetContacts(ctx context.Context, username string) ([]ContactList, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	VerifyUser(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
