// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    password
) VALUES ($1, $2) 
RETURNING username, password, password_changed_at, created_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Password,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, password, password_changed_at, created_at FROM users
WHERE username = $1 AND 
password= $2 LIMIT 1
`

type GetUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Password,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one
SELECT username, password, password_changed_at, created_at FROM users
WHERE username = $1
limit 1
`

func (q *Queries) VerifyUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, verifyUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Password,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}
